In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1083, 1916, 5829, 1457],
 [1083, 1916, 5829, 1423],
 [1083, 2648, 5829, 4296],
 [5137, 5826, 9051, 744, 8248],
 [5137, 5826, 9051, 744, 9055],
 [1305, 1083, 6811, 5829, 4095],
 [8788, 8427, 8819, 744]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1083 1916 5829 1457]
 [   0    0    0    0 1083 1916 5829 1423]
 [   0    0    0    0 1083 2648 5829 4296]
 [   0    0    0 5137 5826 9051  744 8248]
 [   0    0    0 5137 5826 9051  744 9055]
 [   0    0    0 1305 1083 6811 5829 4095]
 [   0    0    0    0 8788 8427 8819  744]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 141ms/step


array([[[ 0.04715372, -0.02531433,  0.01859036, -0.00124716,
         -0.04643347, -0.0389346 ,  0.02682295,  0.03437194,
          0.01287656, -0.01205983],
        [ 0.04715372, -0.02531433,  0.01859036, -0.00124716,
         -0.04643347, -0.0389346 ,  0.02682295,  0.03437194,
          0.01287656, -0.01205983],
        [ 0.04715372, -0.02531433,  0.01859036, -0.00124716,
         -0.04643347, -0.0389346 ,  0.02682295,  0.03437194,
          0.01287656, -0.01205983],
        [ 0.04715372, -0.02531433,  0.01859036, -0.00124716,
         -0.04643347, -0.0389346 ,  0.02682295,  0.03437194,
          0.01287656, -0.01205983],
        [-0.02134278,  0.0171623 , -0.00206641,  0.00505654,
          0.04052592, -0.01667912, -0.0043277 , -0.03346749,
         -0.01701788,  0.03695085],
        [-0.01330279,  0.0035613 ,  0.00331821, -0.01861678,
         -0.01166136,  0.00815226, -0.0265241 ,  0.00840385,
         -0.04887605,  0.02526914],
        [ 0.01689066,  0.01888273, -0.01868414,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 1083, 1916, 5829, 1457])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[ 0.04715372, -0.02531433,  0.01859036, -0.00124716, -0.04643347,
        -0.0389346 ,  0.02682295,  0.03437194,  0.01287656, -0.01205983],
       [ 0.04715372, -0.02531433,  0.01859036, -0.00124716, -0.04643347,
        -0.0389346 ,  0.02682295,  0.03437194,  0.01287656, -0.01205983],
       [ 0.04715372, -0.02531433,  0.01859036, -0.00124716, -0.04643347,
        -0.0389346 ,  0.02682295,  0.03437194,  0.01287656, -0.01205983],
       [ 0.04715372, -0.02531433,  0.01859036, -0.00124716, -0.04643347,
        -0.0389346 ,  0.02682295,  0.03437194,  0.01287656, -0.01205983],
       [-0.02134278,  0.0171623 , -0.00206641,  0.00505654,  0.04052592,
        -0.01667912, -0.0043277 , -0.03346749, -0.01701788,  0.03695085],
       [-0.01330279,  0.0035613 ,  0.00331821, -0.01861678, -0.01166136,
         0.00815226, -0.0265241 ,  0.00840385, -0.04887605,  0.02526914],
       [ 0.01689066,  0.01888273, -0.01868414,  0.02992656,  0.040768  ,
         0.03680626,  0.04830131,  0.00591991